version: 0.0
os: linux
files:
  - source: /target/lavagna.war
    destination: /usr/share/tomcat/webapps/lavagna.war
permissions: 
  - object: / 
    pattern: "**" 
    owner: tomcat 
    group: tomcat
