version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
    - echo "Test"
  build:
    commands:
    - mvn clean install
  post_build:
    command:
    - echo "Test2"
    - mv /target/lavagna ./
artifacts:
  files:
    - appspec.yml
    - target/lavagna.war
