version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
    - echo "Test"
  build:
    commands:
    - mvn clean prepare-package war:exploded
  post_build:
    command:
    - mv /target/lavagna .
artifacts:
  type: zip
  files:
    - 'ROOT/WEB-INF/**/*'
    - 'ROOT/WEB-INF/classes/*'
    - 'ROOT/WEB-INF/classes/**/*'
    - 'ROOT/WEB-INF/lib/*'
    - 'ROOT/WEB-INF/lib-provided/*'
    - 'ROOT/WEB-INF/js/*'
    - 'ROOT/org/springframework/boot/loader/*'